title: "Dr. Your Name"
description: "PhD in Computer Science — Research, Publications, Teaching"
url: ""        # add custom domain later, else leave blank
baseurl: ""    # keep empty for https://YOURUSERNAME.github.io

remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-scholar

markdown: kramdown
kramdown:
  input: GFM

collections:
  publications:
    output: true
    permalink: /publications/:title/
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope: {path: "", type: "pages"}
    values: {layout: single, classes: wide}
  - scope: {path: "", type: "publications"}
    values: {layout: single}
  - scope: {path: "", type: "projects"}
    values: {layout: single}

author:
  name: "Dr. Your Name"
  avatar: "/assets/img/profile.jpg"
  bio: "PhD Candidate in Computer Science at Your University. Research in ML/Systems."
  location: "City, Country"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.email@university.edu"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "ORCID"
      icon: "fas fa-id-badge"
      url: "https://orcid.org/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-handle"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/your-handle/"

# jekyll-scholar
scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  query: "@*"
  sort_by: year, month
  order: descending

google_analytics: ""   # e.g., G-XXXXXXX
permalink: /:categories/:title/
