title: "Dr. Lars E. O. Jacobson"
description: "PhD in Computer Science — research, publications, projects"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"   # try "default", "contrast", "dark"

author:
  name: "Dr. Lars E. O. Jacobson"
  avatar: "/assets/img/profile.jpg"
  bio: "PhD candidate in Computer Science. Interests: trustworthy ML, temporal modelling, ML systems."
  location: "Varberg, Sweden"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:lars.jacobson@gmail.com"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "ORCID"
      icon: "fas fa-id-badge"
      url: "https://orcid.org/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/<your-handle>"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/<your-handle>/"

# Optional
logo: /assets/img/logo.svg
favicon: /assets/img/favicon.png