title: "Dr. Your Name"
description: "PhD in Computer Science — Research, Publications, Teaching"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-scholar

collections:
  publications:
    output: true
    permalink: /publications/:title/
  projects:
    output: true
    permalink: /projects/:title/

author:
  name: "Dr. Your Name"
  avatar: "/assets/img/profile.jpg"
  bio: "PhD Candidate in Computer Science, Your University."
  location: "City, Country"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-handle"
