main:
  - title: "Home"
    url: /
  - title: "Research"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /projects/
  - title: "Teaching"
    url: /teaching/
  - title: "Resources"
    url: /resources/